// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cttaphbzhmheecbqhtjj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0dGFwaGJ6aG1oZWVjYnFodGpqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg0NjQyMjIsImV4cCI6MjA1NDA0MDIyMn0.UkexDbAb6iJ5vF9qJX8qzh_MKWuruDc2c_QOlAd4MBs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);